const express=require("express");const http=require("http");const{Server}=require("socket.io");const app=express();const server=http.createServer(app);const io=new Server(server);app.use(express.static("public"));const rooms={};const SUITS=["♠","♥","♦","♣"];const RANKS=["7","8","9","J","Q","K","10","A"];const NORMAL_POINTS={"7":0,"8":0,"9":0,"J":2,"Q":3,"K":4,"10":10,"A":11};const TRUMP_POINTS={"7":0,"8":0,"Q":3,"K":4,"10":10,"A":11,"9":14,"J":20};const NORMAL_ORDER={"7":1,"8":2,"9":3,"J":4,"Q":5,"K":6,"10":7,"A":8};const TRUMP_ORDER={"7":1,"8":2,"Q":3,"K":4,"10":5,"A":6,"9":7,"J":8};const DECLARATION_ORDER=["7","8","9","10","J","Q","K","A"];
function createDeck(){let deck=[];for(let suit of SUITS){for(let rank of RANKS){deck.push({suit,rank,text:rank+suit})}}return deck}
function shuffle(deck){for(let i=deck.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}return deck}
function cardPoints(card,trump){return card.suit===trump?TRUMP_POINTS[card.rank]:NORMAL_POINTS[card.rank]}
function cardPower(card,trump){return card.suit===trump?TRUMP_ORDER[card.rank]+100:NORMAL_ORDER[card.rank]}
function checkDeclarations(hand,trump){let d=[];d.push(...checkBela(hand,trump));d.push(...checkFourOfKind(hand));d.push(...checkSequences(hand));return d}
function checkBela(hand,trump){const k=hand.some(c=>c.suit===trump&&c.rank==="K");const q=hand.some(c=>c.suit===trump&&c.rank==="Q");return k&&q?[{name:"Bela",points:20,cards:["K"+trump,"Q"+trump]}]:[]}
function checkFourOfKind(hand){let g={},r=[];hand.forEach(c=>{if(!g[c.rank])g[c.rank]=[];g[c.rank].push(c)});Object.keys(g).forEach(rank=>{if(g[rank].length===4){let p=100;if(rank==="J")p=200;if(rank==="9")p=150;if(rank==="7"||rank==="8")p=0;if(p>0)r.push({name:"4x "+rank,points:p,cards:g[rank].map(c=>c.text)})}});return r}
function checkSequences(hand){let result=[];SUITS.forEach(suit=>{let cards=hand.filter(c=>c.suit===suit).sort((a,b)=>DECLARATION_ORDER.indexOf(a.rank)-DECLARATION_ORDER.indexOf(b.rank));let run=[];cards.forEach(card=>{if(run.length===0){run.push(card);return}let prev=DECLARATION_ORDER.indexOf(run[run.length-1].rank);let cur=DECLARATION_ORDER.indexOf(card.rank);if(cur===prev+1)run.push(card);else{addSeq(run,result);run=[card]}});addSeq(run,result)});return result}
function addSeq(run,result){if(run.length<3)return;let p=20;if(run.length===4)p=50;if(run.length>=5)p=100;result.push({name:run.length+" u nizu",points:p,cards:run.map(c=>c.text)})}
function totalDeclarationPoints(d){return d.reduce((s,x)=>s+x.points,0)}
function createRoom(id){rooms[id]={id,players:[],hands:{},started:false,phase:"waiting",trump:null,trumpChooserIndex:0,turnIndex:0,currentTrick:[],trickNumber:0,roundPoints:{A:0,B:0},totalPoints:{A:0,B:0},declarations:{A:0,B:0},declaredPlayers:{},playerDeclarations:{}}}
function getTeamByIndex(i){return i%2===0?"A":"B"}function getRoom(s){return rooms[s.data.roomId]}function getCurrentPlayer(r){return r.players[r.turnIndex]}function getTeamBySocketId(r,id){let i=r.players.findIndex(p=>p.id===id);return getTeamByIndex(i)}
function sendRoomState(id){const r=rooms[id];if(!r)return;io.to(id).emit("roomState",{roomId:r.id,players:r.players.map((p,i)=>({name:p.name,index:i+1,team:getTeamByIndex(i)})),count:r.players.length,phase:r.phase,trump:r.trump,turnName:r.players[r.turnIndex]?.name||"",currentTrick:r.currentTrick.map(t=>({player:t.playerName,card:t.card})),trickNumber:r.trickNumber,roundPoints:r.roundPoints,totalPoints:r.totalPoints,declarations:r.declarations})}
function resetRound(r){r.hands={};r.phase="chooseTrump";r.trump=null;r.trumpChooserIndex=0;r.turnIndex=0;r.currentTrick=[];r.trickNumber=0;r.roundPoints={A:0,B:0};r.declarations={A:0,B:0};r.declaredPlayers={};r.playerDeclarations={}}
function dealCards(id){const r=rooms[id];if(!r||r.players.length!==4)return;resetRound(r);const deck=shuffle(createDeck());r.players.forEach((p,i)=>{r.hands[p.id]=deck.slice(i*8,i*8+8)});r.started=true;r.players.forEach(p=>io.to(p.id).emit("yourCards",r.hands[p.id]));io.to(id).emit("gameStarted",{message:"Karte su podijeljene. Biramo adut."});askTrump(id);sendRoomState(id)}
function askTrump(id){const r=rooms[id];if(!r)return;r.phase="chooseTrump";const p=r.players[r.trumpChooserIndex];io.to(id).emit("logMessage",p.name+" bira adut.");io.to(p.id).emit("chooseTrump",{suits:SUITS,canPass:true});sendRoomState(id)}
function chooseTrump(s,trump){const r=getRoom(s);if(!r||r.phase!=="chooseTrump")return;const chooser=r.players[r.trumpChooserIndex];if(!chooser||chooser.id!==s.id){s.emit("errorMessage","Nisi ti na redu za biranje aduta.");return}if(trump==="pass"){io.to(r.id).emit("logMessage",chooser.name+" kaže dalje.");r.trumpChooserIndex++;if(r.trumpChooserIndex>=4){r.trumpChooserIndex=0;io.to(r.id).emit("logMessage","Nitko nije odabrao. Prvi igrač mora odabrati adut.")}askTrump(r.id);return}if(!SUITS.includes(trump)){s.emit("errorMessage","Neispravan adut.");return}r.trump=trump;r.phase="play";r.turnIndex=r.trumpChooserIndex;io.to(r.id).emit("trumpSelected",{trump,player:chooser.name});io.to(r.id).emit("logMessage",chooser.name+" je odabrao adut: "+trump+".");sendRoomState(r.id)}
function playerHasSuit(h,suit){return h.some(c=>c.suit===suit)}function playerHasTrump(h,trump){return h.some(c=>c.suit===trump)}
function isLegalCard(r,id,card){const h=r.hands[id];if(!h)return{ok:false,message:"Nemaš karte."};const real=h.find(c=>c.text===card.text);if(!real)return{ok:false,message:"Nemaš tu kartu."};if(r.currentTrick.length===0)return{ok:true};const lead=r.currentTrick[0].card.suit;if(real.suit===lead)return{ok:true};if(playerHasSuit(h,lead))return{ok:false,message:"Moraš pratiti boju: "+lead};if(lead!==r.trump&&real.suit!==r.trump&&playerHasTrump(h,r.trump))return{ok:false,message:"Nemaš traženu boju, moraš rezati adutom."};return{ok:true}}
function playCard(s,card){const r=getRoom(s);if(!r||r.phase!=="play")return;const cp=getCurrentPlayer(r);if(!cp||cp.id!==s.id){s.emit("errorMessage","Nisi na potezu.");return}const legal=isLegalCard(r,s.id,card);if(!legal.ok){s.emit("errorMessage",legal.message);return}const h=r.hands[s.id];const i=h.findIndex(c=>c.text===card.text);const played=h.splice(i,1)[0];r.currentTrick.push({playerId:s.id,playerName:s.data.playerName,playerIndex:r.turnIndex,team:getTeamByIndex(r.turnIndex),card:played});s.emit("yourCards",h);io.to(r.id).emit("cardPlayed",{player:s.data.playerName,card:played,trick:r.currentTrick});if(r.currentTrick.length===4)finishTrick(r);else{r.turnIndex=(r.turnIndex+1)%4;io.to(r.id).emit("turnUpdate",{turnName:getCurrentPlayer(r).name})}sendRoomState(r.id)}
function finishTrick(r){const lead=r.currentTrick[0].card.suit;let winner=r.currentTrick[0];for(let play of r.currentTrick){const card=play.card,wc=winner.card;if(card.suit===r.trump&&wc.suit!==r.trump)winner=play;else if(card.suit===wc.suit&&cardPower(card,r.trump)>cardPower(wc,r.trump))winner=play;else if(card.suit===lead&&wc.suit!==r.trump&&wc.suit!==lead)winner=play}let pts=0;for(let p of r.currentTrick)pts+=cardPoints(p.card,r.trump);r.trickNumber++;if(r.trickNumber===8)pts+=10;r.roundPoints[winner.team]+=pts;r.turnIndex=winner.playerIndex;io.to(r.id).emit("trickFinished",{winner:winner.playerName,team:winner.team,points:pts,roundPoints:r.roundPoints});io.to(r.id).emit("logMessage","Štih nosi "+winner.playerName+" za Tim "+winner.team+". Bodovi: "+pts);r.currentTrick=[];if(r.trickNumber>=8)finishRound(r);else io.to(r.id).emit("turnUpdate",{turnName:getCurrentPlayer(r).name})}
function declarePoints(s){const r=getRoom(s);if(!r||r.phase!=="play")return;if(r.declaredPlayers[s.id]){s.emit("errorMessage","Već si provjerio zvanja u ovoj rundi.");return}if(r.currentTrick.length>0||r.trickNumber>0){s.emit("errorMessage","Zvanja se mogu provjeriti samo prije prve karte.");return}const hand=r.hands[s.id]||[];const team=getTeamBySocketId(r,s.id);const declarations=checkDeclarations(hand,r.trump);const points=totalDeclarationPoints(declarations);r.declaredPlayers[s.id]=true;r.playerDeclarations[s.id]=declarations;if(points<=0){s.emit("errorMessage","Nemaš zvanja u ovoj rundi.");sendRoomState(r.id);return}r.declarations[team]+=points;s.emit("yourDeclarations",{declarations,points});io.to(r.id).emit("declarationMade",{player:s.data.playerName,team,points,declarations});io.to(r.id).emit("logMessage",s.data.playerName+" ima zvanja: "+declarations.map(d=>d.name+" ("+d.points+")").join(", ")+". Tim "+team+" +"+points+".");sendRoomState(r.id)}
function finishRound(r){r.phase="roundEnd";const a=r.roundPoints.A+r.declarations.A,b=r.roundPoints.B+r.declarations.B;r.totalPoints.A+=a;r.totalPoints.B+=b;io.to(r.id).emit("roundFinished",{roundPoints:r.roundPoints,declarations:r.declarations,added:{A:a,B:b},totalPoints:r.totalPoints});io.to(r.id).emit("logMessage","Kraj runde. Tim A +"+a+", Tim B +"+b+".");if(r.totalPoints.A>=1001||r.totalPoints.B>=1001){r.phase="gameEnd";let w=r.totalPoints.A>r.totalPoints.B?"A":"B";io.to(r.id).emit("gameFinished",{winner:w,totalPoints:r.totalPoints});io.to(r.id).emit("logMessage","KRAJ IGRE! Pobijedio je Tim "+w+".");sendRoomState(r.id);return}setTimeout(()=>dealCards(r.id),5000);sendRoomState(r.id)}
io.on("connection",s=>{console.log("Igrač spojen:",s.id);s.on("joinRoom",d=>{const roomId=d.roomId,playerName=d.playerName;if(!roomId||!playerName)return;if(!rooms[roomId])createRoom(roomId);const r=rooms[roomId];if(r.started){s.emit("errorMessage","Igra je već počela.");return}if(r.players.length>=4){s.emit("errorMessage","Soba je puna.");return}r.players.push({id:s.id,name:playerName});s.join(roomId);s.data.roomId=roomId;s.data.playerName=playerName;io.to(roomId).emit("roomUpdate",{roomId,players:r.players.map((p,i)=>({name:p.name,team:getTeamByIndex(i),index:i+1})),count:r.players.length});io.to(roomId).emit("logMessage",playerName+" se spojio. Igrača: "+r.players.length+"/4.");if(r.players.length===4)dealCards(roomId);sendRoomState(roomId)});s.on("chooseTrump",t=>chooseTrump(s,t));s.on("setTrump",t=>chooseTrump(s,t));s.on("playCard",c=>playCard(s,c));s.on("declareBela",()=>declarePoints(s));s.on("declarePoints",()=>declarePoints(s));s.on("disconnect",()=>{const id=s.data.roomId;if(!id||!rooms[id])return;const r=rooms[id];r.players=r.players.filter(p=>p.id!==s.id);io.to(id).emit("errorMessage",(s.data.playerName||"Igrač")+" je izašao iz sobe.");io.to(id).emit("roomUpdate",{roomId:id,players:r.players.map((p,i)=>({name:p.name,team:getTeamByIndex(i),index:i+1})),count:r.players.length});if(r.players.length===0)delete rooms[id]})});
const PORT=process.env.PORT||3000;server.listen(PORT,"0.0.0.0",()=>console.log("Bela Online radi na portu "+PORT));
